# Generated by Django 4.2.11 on 2025-05-05 18:41

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890abcdef', length=10, max_length=30, prefix='var', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_review', 'IN Review'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('published', 'Published')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(3, '★★★✩✩'), (1, '★✩✩✩✩'), (2, '★★✩✩✩'), (4, '★★★★✩'), (5, '★★★★★')], default=None, upload_to=''),
        ),
    ]
