# Generated by Django 4.2.11 on 2025-05-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'IN Review'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(4, '★★★★✩'), (2, '★★✩✩✩'), (5, '★★★★★'), (1, '★✩✩✩✩'), (3, '★★★✩✩')], default=None, upload_to=''),
        ),
    ]
