# Generated by Django 4.2.11 on 2025-05-27 12:32

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=products.models.default_expected_delivery),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft'), ('in_review', 'IN Review'), ('disabled', 'Disabled')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(4, '★★★★✩'), (5, '★★★★★'), (3, '★★★✩✩'), (2, '★★✩✩✩'), (1, '★✩✩✩✩')], default=None, upload_to=''),
        ),
    ]
