# Generated by Django 4.2.11 on 2025-05-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productvariant_size_productvariant_vid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('in_review', 'IN Review'), ('draft', 'Draft'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(2, '★★✩✩✩'), (5, '★★★★★'), (3, '★★★✩✩'), (4, '★★★★✩'), (1, '★✩✩✩✩')], default=None, upload_to=''),
        ),
    ]
