# Generated by Django 4.2.11 on 2025-05-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_expected_delivery_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'IN Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(2, '★★✩✩✩'), (5, '★★★★★'), (3, '★★★✩✩'), (4, '★★★★✩'), (1, '★✩✩✩✩')], default=None, upload_to=''),
        ),
    ]
