# Generated by Django 4.2.11 on 2025-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_remove_product_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'IN Review'), ('rejected', 'Rejected'), ('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(2, '★★✩✩✩'), (3, '★★★✩✩'), (1, '★✩✩✩✩'), (4, '★★★★✩'), (5, '★★★★★')], default=None, upload_to=''),
        ),
    ]
