# Generated by Django 4.2.11 on 2025-05-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/media_library/')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'IN Review'), ('published', 'Published'), ('draft', 'Draft'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(5, '★★★★★'), (1, '★✩✩✩✩'), (3, '★★★✩✩'), (4, '★★★★✩'), (2, '★★✩✩✩')], default=None, upload_to=''),
        ),
    ]
