# Generated by Django 4.2.11 on 2025-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('published', 'Published'), ('in_review', 'IN Review'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(1, '★✩✩✩✩'), (4, '★★★★✩'), (2, '★★✩✩✩'), (5, '★★★★★'), (3, '★★★✩✩')], default=None, upload_to=''),
        ),
    ]
