# Generated by Django 4.2.11 on 2025-06-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'IN Review'), ('draft', 'Draft'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(3, '★★★✩✩'), (2, '★★✩✩✩'), (1, '★✩✩✩✩'), (5, '★★★★★'), (4, '★★★★✩')], default=None, upload_to=''),
        ),
    ]
