# Generated by Django 4.2.11 on 2025-06-07 07:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('in_review', 'IN Review'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(4, '★★★★✩'), (1, '★✩✩✩✩'), (3, '★★★✩✩'), (2, '★★✩✩✩'), (5, '★★★★★')], default=None, upload_to=''),
        ),
    ]
