# Generated by Django 4.2.11 on 2025-06-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_about_content_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsreviews',
            name='verified_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('disabled', 'Disabled'), ('in_review', 'IN Review'), ('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '★✩✩✩✩'), (2, '★★✩✩✩'), (3, '★★★✩✩'), (4, '★★★★✩'), (5, '★★★★★')], default=None, null=True),
        ),
    ]
