# Generated by Django 4.2.11 on 2025-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_product_status_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('in_review', 'IN Review'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
