# Generated by Django 4.2.11 on 2025-06-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cart_subtotal_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'IN Review'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
