# Generated by Django 4.2.11 on 2025-06-14 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_time',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft'), ('in_review', 'IN Review'), ('disabled', 'Disabled')], default='published', max_length=10),
        ),
    ]
