# Generated by Django 4.2.11 on 2025-06-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order_expected_delivery_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_popup_title', models.CharField(default='Get 10% OFF your first order', max_length=200)),
                ('discount_popup_subtitle', models.CharField(default='Sign up and unlock your instant discount.', max_length=200)),
                ('discount_popup_email_note', models.CharField(default='You are signing up to receive communication via email and can unsubscribe at any time.', max_length=300)),
                ('promo_strip_text', models.CharField(default='Flat 10% Off on Watches | Use code: SYLVIO10', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'IN Review'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
